### ISSUE TITLE
Add command line option to select which modules to adapt

### ISSUE THREAD

**Issue by lambdabaa** [jrburke/adapt-pkg-main#2]
This is coming up because of

```
/home/gareth/Documents/simplestform/.tup/mnt/@tupjob-49105/home/gareth/Documents/simplestform/node_modules/babel-core.js:1
(function (exports, require, module, __filename, __dirname) { define(['./babel
                                                              ^
ReferenceError: define is not defined
    at Object.<anonymous> (/home/gareth/Documents/simplestform/.tup/mnt/@tupjob-49105/home/gareth/Documents/simplestform/node_modules/babel-core.js:1:63)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/gareth/Documents/simplestform/.tup/mnt/@tupjob-49105/home/gareth/Documents/simplestform/node_modules/babel/bin/babel/index.js:5:24)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

which happens since `babel-core` is being used from node, but it's being adapted/transformed to prime it for amd/browser usage. When someone (in this case babel) tries to `require('babel-core')` from within node, the amd wrapper chokes.

**Comment by lambdabaa** [comment]
Ideally it would just create the <package>.js files that I specify and not transform all of them.
